"""Remove last_login column from User model

Revision ID: 42a52e38a3a0
Revises: d8972633362a
Create Date: 2024-08-14 15:47:31.695122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a52e38a3a0'
down_revision = 'd8972633362a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=25),
               existing_nullable=True)
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=25),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
